on:
  schedule:
    - cron: "5 * * * *"
name: Daily Jobs
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Renovate
        uses: docker://renovate/renovate:19.133-slim@sha256:9b04159c7acf57a629cf25bcfe4eff648669bd44006508f272046539ca67c02a
        env:
          RENOVATE_REPOSITORIES: LisinIwan/Test-App
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_AUTOMERGE: true # optional, see below
